# Generated by Django 2.2.17 on 2020-12-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201220_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.IntegerField(default=0),
        ),
    ]
