# Generated by Django 2.2.17 on 2020-11-29 11:00

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=255)),
                ('amount_due', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('transaction_description', models.TextField(max_length=2000)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('issuer', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('p', 'paid'), ('u', 'unpaid')], default='u', max_length=1)),
            ],
        ),
    ]
